# Generated by Django 5.2.3 on 2025-06-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField()),
            ],
            options={
                'verbose_name': 'login_Information',
                'verbose_name_plural': 'login_Informations',
                'db_table': 'UserInfo',
                'ordering': ('username',),
            },
        ),
    ]
